export default {
    GET_USERS: 'GET_USERS',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_USER_ALBUMS:'GET_USER_ALBUMS',
    GET_ALBUM_PHOTOS:'GET_ALBUM_PHOTOS',
    GET_USER_POSTS:'GET_USER_POSTS',
    GET_POST_COMMENTS:'GET_POST_COMMENTS'
}